"""Minimal relay server package."""

from .app import build_http_server, build_health_payload, run_relay_server, start_relay_server
from .auth import token_fingerprint, validate_transport_token
from .config import RelayServerConfig
from .delivery import RelayPacketDeliverer, build_dispatch_request_from_packet
from .loopback import LoopbackRelayServer
from .packet_store import (
    AcceptedRelayPacket,
    InMemoryAcceptedPacketStore,
    PersistentAcceptedPacketStore,
    RelayDeliveryAttempt,
)
from .pc_command_store import (
    InMemoryPcCommandStore,
    PcCommandConflictError,
    PcCommandRecord,
    PcCommandUnknownError,
    PersistentPcCommandStore,
)
from .pc_control_protocol import (
    PC_CONTROL_SCHEMA_VERSION,
    PcCommandAckMessage as PcControlCommandAckMessage,
    PcCommandDispatchMessage as PcControlCommandDispatchMessage,
    PcControlProtocolError,
    PcErrorMessage as PcControlErrorMessage,
    PcHeartbeatMessage as PcControlHeartbeatMessage,
    PcHelloAckMessage as PcControlHelloAckMessage,
    PcHelloMessage as PcControlHelloMessage,
    PcWorkspaceSnapshotMessage as PcControlWorkspaceSnapshotMessage,
    build_command_ack as build_pc_control_command_ack,
    build_command_dispatch as build_pc_control_command_dispatch,
    build_heartbeat as build_pc_control_heartbeat,
    build_pc_error as build_pc_control_error,
    build_pc_hello as build_pc_control_hello,
    build_pc_hello_ack as build_pc_control_hello_ack,
    build_workspace_snapshot as build_pc_control_workspace_snapshot,
    parse_pc_control_client_message,
    parse_pc_control_server_message,
)
from .pc_control_runtime import (
    PcCommandDispatchValidationError,
    PcControlRuntime,
    build_pc_control_runtime,
)
from .pc_credential_registry import (
    InMemoryPcCredentialRegistry,
    PcCredentialRecord,
    PersistentPcCredentialRegistry,
    hash_transport_token,
)
from .pc_node_store import InMemoryPcNodeStore, PcNodeFenceError, PcNodeRecord, PersistentPcNodeStore
from .phase3_emitter import (
    build_default_phase3_timeline_items,
    build_phase3_assistant_reply_preview_item,
    build_phase3_paused_hint_item,
    build_phase3_question_prompt_item,
    build_phase3_question_state,
    build_phase3_session_snapshot_update,
    build_phase3_state_transition_item,
    build_phase3_state_transition_update,
    build_phase3_terminal_summary_item,
    build_phase3_timeline_append_update,
    normalize_phase3_paused_from_status,
    normalize_phase3_wire_status,
    project_phase3_session_snapshot,
    project_phase3_state_transition_delta,
    project_phase3_timeline_append_delta,
)
from .phase3_fixture_package import (
    Phase3FixtureManifest,
    Phase3FixtureManifestEntry,
    Phase3FixtureUnit,
    iter_phase3_fixture_units,
    load_phase3_fixture_manifest,
    load_phase3_fixture_unit,
    phase3_fixture_root,
)
from .phase3_subscription import (
    Phase3SessionDetailProvider,
    Phase3SubscribeSessionDetailRequest,
    Phase3SubscribeSessionDetailResult,
    Phase3SubscriptionError,
    ThreadStorePhase3SessionDetailProvider,
    parse_phase3_subscribe_request,
)
from .protocol import (
    ProtocolValidationError,
    RelayErrorMessage,
    RelayHelloAckMessage,
    RelayHelloMessage,
    RelayPacketAckMessage,
    RelayPacketMessage,
    RelayPingMessage,
    RelaySessionUpdateMessage,
    build_error_message,
    build_hello_ack,
    build_packet_ack,
    build_session_update,
    parse_client_message,
    parse_server_message,
)
from .session_store import InMemorySessionStore, PersistentSessionStore, RelaySession
from .workspace_inventory_store import (
    InMemoryWorkspaceInventoryStore,
    PcWorkspaceRecord,
    PersistentWorkspaceInventoryStore,
    WorkspaceInventoryConflictError,
)

__all__ = [
    "AcceptedRelayPacket",
    "InMemoryAcceptedPacketStore",
    "InMemoryPcCommandStore",
    "InMemoryPcCredentialRegistry",
    "InMemoryPcNodeStore",
    "InMemorySessionStore",
    "InMemoryWorkspaceInventoryStore",
    "LoopbackRelayServer",
    "PC_CONTROL_SCHEMA_VERSION",
    "PcCommandConflictError",
    "PcCommandDispatchValidationError",
    "PcCommandRecord",
    "PcCommandUnknownError",
    "PcControlCommandAckMessage",
    "PcControlCommandDispatchMessage",
    "PcControlErrorMessage",
    "PcControlHeartbeatMessage",
    "PcControlHelloAckMessage",
    "PcControlHelloMessage",
    "PcControlProtocolError",
    "PcControlRuntime",
    "PcControlWorkspaceSnapshotMessage",
    "PcCredentialRecord",
    "PcNodeFenceError",
    "PcNodeRecord",
    "PcWorkspaceRecord",
    "PersistentAcceptedPacketStore",
    "PersistentPcCommandStore",
    "PersistentPcCredentialRegistry",
    "PersistentPcNodeStore",
    "PersistentSessionStore",
    "PersistentWorkspaceInventoryStore",
    "Phase3FixtureManifest",
    "Phase3FixtureManifestEntry",
    "Phase3FixtureUnit",
    "Phase3SessionDetailProvider",
    "Phase3SubscribeSessionDetailRequest",
    "Phase3SubscribeSessionDetailResult",
    "Phase3SubscriptionError",
    "ProtocolValidationError",
    "RelayDeliveryAttempt",
    "RelayErrorMessage",
    "RelayHelloAckMessage",
    "RelayHelloMessage",
    "RelayPacketAckMessage",
    "RelayPacketDeliverer",
    "RelayPacketMessage",
    "RelayPingMessage",
    "RelayServerConfig",
    "RelaySession",
    "RelaySessionUpdateMessage",
    "ThreadStorePhase3SessionDetailProvider",
    "WorkspaceInventoryConflictError",
    "build_default_phase3_timeline_items",
    "build_dispatch_request_from_packet",
    "build_error_message",
    "build_health_payload",
    "build_hello_ack",
    "build_http_server",
    "build_packet_ack",
    "build_pc_control_command_ack",
    "build_pc_control_command_dispatch",
    "build_pc_control_error",
    "build_pc_control_heartbeat",
    "build_pc_control_hello",
    "build_pc_control_hello_ack",
    "build_pc_control_runtime",
    "build_pc_control_workspace_snapshot",
    "build_phase3_assistant_reply_preview_item",
    "build_phase3_paused_hint_item",
    "build_phase3_question_prompt_item",
    "build_phase3_question_state",
    "build_phase3_session_snapshot_update",
    "build_phase3_state_transition_item",
    "build_phase3_state_transition_update",
    "build_phase3_terminal_summary_item",
    "build_phase3_timeline_append_update",
    "build_session_update",
    "hash_transport_token",
    "iter_phase3_fixture_units",
    "load_phase3_fixture_manifest",
    "load_phase3_fixture_unit",
    "normalize_phase3_paused_from_status",
    "normalize_phase3_wire_status",
    "parse_client_message",
    "parse_pc_control_client_message",
    "parse_pc_control_server_message",
    "parse_phase3_subscribe_request",
    "parse_server_message",
    "phase3_fixture_root",
    "project_phase3_session_snapshot",
    "project_phase3_state_transition_delta",
    "project_phase3_timeline_append_delta",
    "run_relay_server",
    "start_relay_server",
    "token_fingerprint",
    "validate_transport_token",
]
