"""Minimal relay server package."""

from .app import build_http_server, build_health_payload, run_relay_server, start_relay_server
from .auth import token_fingerprint, validate_transport_token
from .config import RelayServerConfig
from .delivery import RelayPacketDeliverer, build_dispatch_request_from_packet
from .loopback import LoopbackRelayServer
from .phase3_emitter import (
    build_default_phase3_timeline_items,
    build_phase3_assistant_reply_preview_item,
    build_phase3_paused_hint_item,
    build_phase3_question_prompt_item,
    build_phase3_question_state,
    build_phase3_session_snapshot_update,
    build_phase3_state_transition_item,
    build_phase3_state_transition_update,
    build_phase3_terminal_summary_item,
    build_phase3_timeline_append_update,
    normalize_phase3_paused_from_status,
    normalize_phase3_wire_status,
    project_phase3_session_snapshot,
    project_phase3_state_transition_delta,
    project_phase3_timeline_append_delta,
)
from .phase3_subscription import (
    Phase3SessionDetailProvider,
    Phase3SubscribeSessionDetailRequest,
    Phase3SubscribeSessionDetailResult,
    Phase3SubscriptionError,
    ThreadStorePhase3SessionDetailProvider,
    parse_phase3_subscribe_request,
)
from .packet_store import (
    AcceptedRelayPacket,
    InMemoryAcceptedPacketStore,
    PersistentAcceptedPacketStore,
    RelayDeliveryAttempt,
)
from .protocol import (
    ProtocolValidationError,
    RelayErrorMessage,
    RelayHelloMessage,
    RelayHelloAckMessage,
    RelayPacketMessage,
    RelayPacketAckMessage,
    RelayPingMessage,
    RelaySessionUpdateMessage,
    build_error_message,
    build_hello_ack,
    build_packet_ack,
    build_session_update,
    parse_client_message,
    parse_server_message,
)
from .phase3_fixture_package import (
    Phase3FixtureManifest,
    Phase3FixtureManifestEntry,
    Phase3FixtureUnit,
    iter_phase3_fixture_units,
    load_phase3_fixture_manifest,
    load_phase3_fixture_unit,
    phase3_fixture_root,
)
from .session_store import InMemorySessionStore, PersistentSessionStore, RelaySession

__all__ = [
    "AcceptedRelayPacket",
    "RelayDeliveryAttempt",
    "RelayPacketDeliverer",
    "InMemorySessionStore",
    "InMemoryAcceptedPacketStore",
    "PersistentSessionStore",
    "PersistentAcceptedPacketStore",
    "build_default_phase3_timeline_items",
    "build_phase3_assistant_reply_preview_item",
    "build_phase3_paused_hint_item",
    "build_phase3_question_prompt_item",
    "build_phase3_question_state",
    "build_phase3_session_snapshot_update",
    "build_phase3_state_transition_item",
    "build_phase3_state_transition_update",
    "build_phase3_terminal_summary_item",
    "build_phase3_timeline_append_update",
    "LoopbackRelayServer",
    "normalize_phase3_paused_from_status",
    "normalize_phase3_wire_status",
    "ProtocolValidationError",
    "RelayErrorMessage",
    "RelayHelloMessage",
    "RelayHelloAckMessage",
    "RelayPacketMessage",
    "RelayPacketAckMessage",
    "RelayPingMessage",
    "RelaySessionUpdateMessage",
    "RelayServerConfig",
    "RelaySession",
    "Phase3FixtureManifest",
    "Phase3FixtureManifestEntry",
    "Phase3FixtureUnit",
    "Phase3SessionDetailProvider",
    "Phase3SubscribeSessionDetailRequest",
    "Phase3SubscribeSessionDetailResult",
    "Phase3SubscriptionError",
    "build_error_message",
    "build_dispatch_request_from_packet",
    "build_health_payload",
    "build_hello_ack",
    "build_packet_ack",
    "build_session_update",
    "build_http_server",
    "iter_phase3_fixture_units",
    "load_phase3_fixture_manifest",
    "load_phase3_fixture_unit",
    "parse_client_message",
    "parse_server_message",
    "phase3_fixture_root",
    "parse_phase3_subscribe_request",
    "project_phase3_session_snapshot",
    "project_phase3_state_transition_delta",
    "project_phase3_timeline_append_delta",
    "run_relay_server",
    "start_relay_server",
    "ThreadStorePhase3SessionDetailProvider",
    "token_fingerprint",
    "validate_transport_token",
]
