"""Centralized status and backend constants."""

from __future__ import annotations

BACKEND_OPENCODE = "opencode"
BACKEND_CODEX = "codex"
BACKEND_NAMES = {BACKEND_OPENCODE, BACKEND_CODEX}
BACKEND_TRANSPORT_CLI = "cli"
BACKEND_TRANSPORT_SDK = "sdk"
BACKEND_TRANSPORT_NAMES = {BACKEND_TRANSPORT_CLI, BACKEND_TRANSPORT_SDK}

RUN_STATUS_SUCCESS = "success"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_KILLED = "killed"
RUN_STATUS_AWAITING_USER_INPUT = "awaiting_user_input"
RUN_STATUS_PAUSED = "paused"

CURRENT_RUN_STATUSES = {
    RUN_STATUS_SUCCESS,
    RUN_STATUS_FAILED,
    RUN_STATUS_KILLED,
    RUN_STATUS_AWAITING_USER_INPUT,
    RUN_STATUS_PAUSED,
}

THREAD_STATUS_IDLE = "idle"
THREAD_STATUS_ACCEPTED = "accepted"
THREAD_STATUS_RUNNING = "running"
THREAD_STATUS_DONE = "done"
THREAD_STATUS_FAILED = "failed"
THREAD_STATUS_KILLED = "killed"
THREAD_STATUS_AWAITING_USER_INPUT = "awaiting_user_input"
THREAD_STATUS_PAUSED = "paused"

CURRENT_THREAD_STATUSES = {
    THREAD_STATUS_IDLE,
    THREAD_STATUS_ACCEPTED,
    THREAD_STATUS_RUNNING,
    THREAD_STATUS_DONE,
    THREAD_STATUS_FAILED,
    THREAD_STATUS_KILLED,
    THREAD_STATUS_AWAITING_USER_INPUT,
    THREAD_STATUS_PAUSED,
}

FINAL_THREAD_STATUS_BY_RUN_STATUS = {
    RUN_STATUS_SUCCESS: THREAD_STATUS_DONE,
    RUN_STATUS_FAILED: THREAD_STATUS_FAILED,
    RUN_STATUS_KILLED: THREAD_STATUS_KILLED,
    RUN_STATUS_AWAITING_USER_INPUT: THREAD_STATUS_AWAITING_USER_INPUT,
    RUN_STATUS_PAUSED: THREAD_STATUS_PAUSED,
}
